### ISSUE TITLE
インパルス応答のステレオ対応

### ISSUE THREAD

**Issue by GoTojo** [Kashiwade/Kashiwade#1]
"現在はモノラルファイルのL, Rで行っているため、ステレオ対応を調査、実装対応。
用意されているAPIで実現できるはず。"

**Comment by JunichiMinamino** [comment]
（10/6 現在）こちらを優先調査します。
該当修正箇所は ConvolutionInstrument.m です。

**Comment by JunichiMinamino** [comment]
10/7 のコミットで対応しました。
あとは聴いていただいての確認になります。

**Comment by JunichiMinamino** [comment]
大丈夫そうですので、閉じます。
