### ISSUE TITLE
地図の縮尺を変えるとピンの位置がずれる

### ISSUE THREAD

**Issue by GoTojo** [Kashiwade/Kashiwade#12]
広範囲が見えるよう縮尺を変えると位置がずれる
真鶴は海の上になってしまう

->デフォルトのピンでいいかも

**Comment by JunichiMinamino** [comment]
現状は、ピンを指定の画像で表示しているのですが、それが問題だと思いますので、おいおい調査します。

**Comment by JunichiMinamino** [comment]
ピンの画像を加工することで、見かけ上のズレは小さくなりました。

**Comment by JunichiMinamino** [comment]
大丈夫そうですので、閉じます。
