### ISSUE TITLE
写真とスライダがかぶっている

### ISSUE THREAD

**Issue by GoTojo** [Kashiwade/Kashiwade#6]

**Comment by JunichiMinamino** [comment]
２つあるスライダーのうち、下の方のは、インパルス応答のステレオ対応化により不要になる予定です。

**Comment by GoTojo** [comment]
Xcode7でサイズが小さくなる不具合が原因だったのでしょうか?
現在かぶってない気がします

**Comment by JunichiMinamino** [comment]
おそらくそうですね。
あと、ステレオ対応にした現状は、下のLRのスライダーは使用していないので、削除する方向になるかもしれないです。
画面全体のUI配置も考えていきたいところです。

**Comment by GoTojo** [comment]
とりあえずクローズしますね

**Comment by GoTojo** [comment]
iPhone4Sとかだとやっぱりかぶる
バランススライダーがなくなる予定なのでとりあえずクローズしたままにしておく
